<div class="entry">
<h1 class="entry--title">Hola <?= $name ?></h1>
	<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ea a beatae aut consequuntur. Facilis ex, officiis explicabo voluptates accusamus repudiandae odio itaque, rerum reiciendis, similique beatae sit tempore excepturi fuga.
	Harum numquam nisi quos, perspiciatis reprehenderit laborum iste officia repellat eius reiciendis blanditiis consectetur nulla animi hic enim sed earum, rerum est, unde dolorum labore natus aliquid? Laudantium, amet earum.
	Suscipit, a est? Ipsa similique tenetur voluptates consectetur ipsam facere repellendus optio nisi inventore consequatur provident perspiciatis ad ratione quia magnam quis autem, delectus alias adipisci ea esse nihil voluptas?
	Temporibus aspernatur fuga officiis pariatur quo quae! Ratione velit vero illo facilis facere atque ipsam, necessitatibus itaque culpa blanditiis maiores adipisci nesciunt voluptatibus non nemo aut minus dolorem cupiditate consequuntur!
	Animi similique hic ducimus velit pariatur! Quibusdam deserunt odit libero ex, quis iure laborum quia repudiandae porro rerum similique, nam eum. Odio nemo fugit eos, voluptatum ipsa consectetur laborum molestias.
	Sint quae enim ipsa, quisquam sed, animi magni non optio corporis itaque error suscipit quis? Harum, quidem commodi officia aperiam consequuntur voluptas, dolor dignissimos in expedita doloremque ad suscipit nisi?
	Odit, dolorum voluptatum? Perspiciatis nemo, ea expedita laudantium tempora voluptatum? Animi voluptatem vel asperiores, officia doloribus optio? Fuga tempora sapiente et, dolorum, vel voluptates voluptatem modi molestias ad provident velit!
	Dicta numquam autem alias exercitationem atque neque delectus. Rem deserunt quis quaerat vitae voluptatem possimus sed incidunt. Aut atque consequuntur pariatur ducimus rerum at delectus alias impedit quas. Architecto, iste!
	Similique sed aut delectus quaerat facere excepturi veritatis, fugiat est odit in, totam nostrum! In praesentium consequuntur cupiditate debitis laudantium dolore, officiis saepe quasi pariatur! Ratione velit perferendis iusto accusamus.
	Fugit officiis nihil earum laudantium, unde, facere expedita hic vitae velit sed reprehenderit est repellat soluta modi! Dignissimos, mollitia dolores itaque ullam molestiae et sit perspiciatis, perferendis inventore magni assumenda.
	Tempora, blanditiis esse placeat rem est autem corrupti labore et totam consequatur accusamus quod incidunt tenetur dolor praesentium delectus iure natus voluptate doloremque voluptatem recusandae excepturi mollitia pariatur! Illo, ipsum!
	Nobis tempora, obcaecati dolores rerum facilis voluptatum molestias impedit. Dicta officia quam incidunt iste sint consequatur ratione perferendis explicabo, ex provident illo eaque animi iusto sapiente? Suscipit nulla voluptatem eius.</p>
</div>

